---
notifications:
  email: false
language: cpp
dist: trusty
sudo: required

# Build matrix
env:
  matrix:
  - TRAVIS_NODE_VERSION="4"
  - TRAVIS_NODE_VERSION="4" ARCH="x86"
  - TRAVIS_NODE_VERSION="6"
  - TRAVIS_NODE_VERSION="6" ARCH="x86"
  - BINARY_BUILDER="true" TRAVIS_NODE_VERSION="8"
  - BINARY_BUILDER="true" TRAVIS_NODE_VERSION="8" ARCH="x86"

cache:
  directories:
    - $HOME/.npm/
    - $HOME/.npm-cache/

before_install:

# download node if testing x86 architecture
- >
  if [[ "$ARCH" == "x86" ]]; then
    EXPANDED_VERSION=$(curl https://semver.io/node/resolve/$TRAVIS_NODE_VERSION);
    echo "EXPANDED_VERSION =" $EXPANDED_VERSION
    BASE_URL=https://nodejs.org/dist/v$EXPANDED_VERSION;
    X86_FILE=node-v$EXPANDED_VERSION-$(node -p "process.platform")-x86;
    echo "X86_FILE =" $X86_FILE;
    wget $BASE_URL/$X86_FILE.tar.gz;
    tar -xf $X86_FILE.tar.gz;
    nvm deactivate;
    export PATH=$X86_FILE/bin:$PATH;
    if [[ $TRAVIS_OS_NAME == "linux" ]]; then sudo apt-get install libudev-dev:i386 g++-multilib; fi
  else
    nvm install $TRAVIS_NODE_VERSION
    if [[ $TRAVIS_OS_NAME == "linux" ]]; then sudo apt-get install libudev-dev; fi
  fi;
- $CXX --version

# Cleanup the output of npm
- npm config set progress false
- npm config set spin false

# print versions
- uname -a
- which node; file `which node`
- node --version
- node -p 'process.platform + "@" + process.arch'
- npm --version

install:
# ensure source install works
- npm install --build-from-source